In [2]:
import pandas as pd
import numpy as np
from darts import TimeSeries
from darts.models import RegressionModel
from darts.utils.timeseries_generation import datetime_attribute_timeseries
from darts.dataprocessing.transformers import Scaler
from darts.metrics import mape
from sklearn.model_selection import TimeSeriesSplit
from joblib import Parallel, delayed
from xgboost import XGBRegressor

#Load the engineered data
df = pd.read_parquet('../../Data/Merged_Data/eaglei_noaa_era5_engineered.parquet')

# Restrict df to years prior to 2022 and after 2019
df = df[df['YEAR'] < 2022]
df = df[df['YEAR'] > 2019]

# We'll focus on Maine, Oregon, Arizona, Nebraska, and South Carolina
df = df[df['STUSPS'].isin(['ME', 'OR', 'AZ', 'NE', 'SC'])]

# Create a new variable 'customers_out_prop" by dividing customers_out by POPULATION
df['customers_out_prop'] = df['customers_out'] / df['POPULATION']

# Create a new variable dividing POPULATION divided by AREA
df['density'] = df['POPULATION'] / df['AREA']

# Note: Not currently including Subregion b/c we'd need to convert to a dummy variable

features_ts = ['event_count SnowIce',
       'event_count Flood', 'event_count Storm', 'event_count Hurricane',
       'event_count Heat', 'event_count Fire', 'event_count Wind',
       'event_count Ocean', 'event_count Other', 't2m', 'sf', 'tp', 't2m_mean',
       't2m_max', 'sf_mean', 'sf_max', 'tp_mean', 'tp_max', 'wind_speed',
       'neighbor_mean_wind_speed', 'neighbor_max_wind_speed', 'sf_12h',
       'sf_24h', 'tp_12h', 'tp_24h']

features_static = ['Pct_Buried_Lines','centroid_longitude','centroid_latitude','density', 'POPULATION']

# Your variable lists
target_col = 'customers_out_prop'
time_col = 'datetime'
id_col = 'fips_code'
forecast_horizon = 4        # 4 timesteps (6-hourly cadence = 24h)

# --- Prepare data grouped by county ---
grouped = dict(tuple(df.groupby(id_col)))

# Convert to Darts TimeSeries objects
series_list = []
past_cov_list = []
static_cov_list = []

for fips, group in grouped.items():
    group = group.sort_values(time_col)
    ts_target = TimeSeries.from_dataframe(group, time_col, target_col)
    ts_covariates = TimeSeries.from_dataframe(group, time_col, features_ts)
    
    series_list.append(ts_target)
    past_cov_list.append(ts_covariates)
    
    # Static covariates are same for all time points in group
    static_cov = group[features_constant].iloc[0]
    static_cov_list.append(static_cov)

# --- Scaling ---
target_scaler = Scaler()
cov_scaler = Scaler()

series_scaled = target_scaler.fit_transform(series_list)
cov_scaled = cov_scaler.fit_transform(past_cov_list)

# --- Assign static covariates ---
for ts, static_cov in zip(series_scaled, static_cov_list):
    ts.static_covariates = static_cov

# --- Transform target series into max-over-next-4-horizon task ---
def to_rolling_max_target(series, horizon):
    y = []
    for i in range(len(series) - horizon):
        y.append(np.max(series[i+1:i+1+horizon].values()))
    time_index = series[:-horizon].time_index
    return TimeSeries.from_times_and_values(time_index, y, static_covariates=series.static_covariates)

target_max_series = [to_rolling_max_target(ts, forecast_horizon) for ts in series_scaled]
cov_trimmed = [ts[:-forecast_horizon] for ts in cov_scaled]

# --- Model setup ---
model = RegressionModel(
    lags=20,
    lags_past_covariates=20,
    model=XGBRegressor(),
    use_static_covariates=True,
    output_chunk_length=1,
    multi_models=False,
    random_state=42,
)

# --- Cross-validation setup ---
tscv = TimeSeriesSplit(n_splits=5)

def run_cv(train_series, train_covs, val_series, val_covs):
    model.fit(
        series=train_series,
        past_covariates=train_covs,
        verbose=False,
    )
    forecasts = model.predict(n=1, series=val_series, past_covariates=val_covs)
    return forecasts

# --- Parallelized cross-validation ---
results = []

for train_idx, val_idx in tscv.split(target_max_series[0]):
    train_series = [ts[train_idx] for ts in target_max_series]
    val_series = [ts[val_idx] for ts in target_max_series]
    train_covs = [ts[train_idx] for ts in cov_trimmed]
    val_covs = [ts[val_idx] for ts in cov_trimmed]
    
    # Each fold runs in parallel
    fold_results = Parallel(n_jobs=-1)(
        delayed(run_cv)(
            [train_series[i] for i in range(len(series_scaled))],
            [train_covs[i] for i in range(len(series_scaled))],
            [val_series[i] for i in range(len(series_scaled))],
            [val_covs[i] for i in range(len(series_scaled))],
        )
    )
    results.append(fold_results)

# --- Evaluate ---
def evaluate(preds, actuals):
    return np.mean([mape(p, a) for p, a in zip(preds, actuals)])

# Example: evaluate last fold
preds = results[-1]
actuals = [ts[val_idx][-1:] for ts in target_max_series]
print("Last fold MAPE:", evaluate(preds, actuals))


KeyboardInterrupt: 

In [29]:
import pandas as pd
import numpy as np
from darts import TimeSeries
from darts.models import RegressionModel
from darts.dataprocessing.transformers import Scaler
from darts.metrics import mape
from sklearn.model_selection import TimeSeriesSplit
from xgboost import XGBRegressor
from joblib import Parallel, delayed
from tqdm import tqdm


#Load the engineered data
df = pd.read_parquet('../../Data/Merged_Data/eaglei_noaa_era5_engineered.parquet')

# Restrict df to years prior to 2022 and after 2019
df = df[df['YEAR'] < 2022]
df = df[df['YEAR'] > 2019]

# We'll focus on Maine, Oregon, Arizona, Nebraska, and South Carolina
df = df[df['STUSPS'].isin(['ME', 'OR', 'AZ', 'NE', 'SC'])]

# Create a new variable 'customers_out_prop" by dividing customers_out by POPULATION
df['customers_out_prop'] = df['customers_out'] / df['POPULATION']

# Create a new variable dividing POPULATION divided by AREA
df['density'] = df['POPULATION'] / df['AREA']

# Note: Not currently including Subregion b/c we'd need to convert to a dummy variable

features_ts = ['event_count SnowIce',
       'event_count Flood', 'event_count Storm', 'event_count Hurricane',
       'event_count Heat', 'event_count Fire', 'event_count Wind',
       'event_count Ocean', 'event_count Other', 't2m', 'sf', 'tp', 't2m_mean',
       't2m_max', 'sf_mean', 'sf_max', 'tp_mean', 'tp_max', 'wind_speed',
       'neighbor_mean_wind_speed', 'neighbor_max_wind_speed', 'sf_12h',
       'sf_24h', 'tp_12h', 'tp_24h']

features_static = ['Pct_Buried_Lines','centroid_longitude','centroid_latitude','density', 'POPULATION']

# --- CONFIG ---
forecast_horizon = 4
lags = 20
n_splits = 5

# --- PREP DATA ---
grouped = dict(tuple(df.groupby('fips_code')))
fips_codes = list(grouped.keys())

series_list, cov_list, static_list = [], [], []

for fips, grp in grouped.items():
    grp = grp.sort_values('datetime')
    ts_target = TimeSeries.from_dataframe(grp, 'datetime', 'customers_out_prop')
    ts_covs = TimeSeries.from_dataframe(grp, 'datetime', features_ts)
    
    series_list.append(ts_target)
    cov_list.append(ts_covs)
    static_list.append(grp[features_static].iloc[0])

# Scale
target_scaler = Scaler()
cov_scaler = Scaler()
series_scaled = target_scaler.fit_transform(series_list)
cov_scaled = cov_scaler.fit_transform(cov_list)

# Attach static covariates
for ts, static in zip(series_scaled, static_list):
    ts = ts.with_static_covariates(static)

# Create max-over-horizon targets
def to_max_series(series, horizon):
    y = [np.max(series[i+1:i+1+horizon].values()) for i in range(len(series)-horizon)]
    time_index = series[:-horizon].time_index
    return TimeSeries.from_times_and_values(time_index, y, static_covariates=series.static_covariates)

target_max = [to_max_series(ts, forecast_horizon) for ts in series_scaled]
cov_trimmed = [ts[:-forecast_horizon] for ts in cov_scaled]

# --- TIME SPLITS ---
tscv = TimeSeriesSplit(n_splits=n_splits)
indices = list(tscv.split(target_max[0]))

# --- RESULTS CONTAINER ---
results = []
final_model = None

# --- CROSS-VALIDATION LOOP ---
for fold, (train_idx, val_idx) in enumerate(tqdm(indices, desc="CV Folds")):
    # Use a reference series to get actual time ranges
    reference_times = target_max[0].time_index
    train_start = reference_times[train_idx[0]]
    train_end = reference_times[train_idx[-1]]
    val_start = reference_times[val_idx[0]]
    val_end = reference_times[val_idx[-1]]

    # Slice all series by time
    train_series = [ts.slice(train_start, train_end) for ts in target_max]
    val_series = [ts.slice(val_start, val_end) for ts in target_max]
    train_covs = [ts.slice(train_start, train_end) for ts in cov_trimmed]
    val_covs = [ts.slice(val_start, val_end) for ts in cov_trimmed]

    model = RegressionModel(
        model=XGBRegressor(n_jobs=-1, random_state=random_state),
        lags=lags,
        lags_past_covariates=lags,
        output_chunk_length=forecast_horizon,
        use_static_covariates=True,
        multi_models=False,
    )

    # Fit once (global)
    model.fit(series=train_series, past_covariates=train_covs, verbose=False)
    final_model = model  # Store last model

    # --- PREDICT PARALLELIZED ---
    def predict_one(i):
        fips = fips_codes[i]
        full_series = series_list[i]  # full target series (train + val)
        covariates = features_ts[i]  # time-varying covariates
        static = features_static[i]    # static covariates
        
        full_series = full_series.with_static_covariates(static)

        results = []

        # Use val_series to define valid forecast windows
        val_start = val_series[i].start_time()
        val_end = val_series[i].end_time()

        timestamps = pd.date_range(
            val_start, 
            val_end - forecast_horizon * full_series.freq, 
            freq=full_series.freq
        )

        print(f"\n[DEBUG] fips={fips}, rolling predictions: {len(timestamps)}")

        for t in timestamps:
            try:
                # Input = all data before t
                input_ts = full_series.drop_after(t)
                input_covs = covariates.drop_after(t)

                # Forecast n steps from that point
                pred = model.predict(
                    n=forecast_horizon,
                    series=input_ts,
                    past_covariates=input_covs,
                    show_warnings=False
                )

                if pred is None or len(pred) < forecast_horizon:
                    continue

                pred_max = float(pred.values().max())

                # True values for same time window
                true_window = full_series.slice(t + full_series.freq, t + forecast_horizon * full_series.freq)

                if len(true_window) < forecast_horizon:
                    continue

                true_max = float(true_window.values().max())

                results.append({
                    "fips_code": fips,
                    "fold": fold,
                    "predicted_max": pred_max,
                    "true_max": true_max,
                    "datetime": t.to_pydatetime()
                })

            except Exception as e:
                print(f"[ERROR] fips={fips}, t={t}: {e}")
                continue

        print(f"[DONE] fips={fips}, predictions: {len(results)}")
        return results





    fold_results = Parallel(n_jobs=-1, backend="loky")(delayed(predict_one)(i) for i in range(len(series_list)))
    results.extend([item for sublist in fold_results for item in sublist])

# --- BUILD RESULTS DATAFRAME ---
cv_results_df = pd.DataFrame(results)

# --- FINAL REGRESSOR PARAMS ---
regressor_params = final_model.model.get_params()

# Output
cv_results_df.head(), regressor_params


CV Folds:   0%|          | 0/5 [00:00<?, ?it/s]ValueError: `static_covariates` must be either a pandas Series, DataFrame or None
ValueError: `static_covariates` must be either a pandas Series, DataFrame or None
ValueError: `static_covariates` must be either a pandas Series, DataFrame or None
ValueError: `static_covariates` must be either a pandas Series, DataFrame or None
ValueError: `static_covariates` must be either a pandas Series, DataFrame or None
CV Folds:   0%|          | 0/5 [00:11<?, ?it/s]


IndexError: list index out of range

In [27]:
cv_results_df

""


In [ ]:
import pandas as pd
import numpy as np
from darts import TimeSeries
from darts.models import RegressionModel
from darts.dataprocessing.transformers import Scaler
from darts.metrics import mape
from sklearn.model_selection import TimeSeriesSplit
from xgboost import XGBRegressor
from joblib import Parallel, delayed
from tqdm import tqdm


#Load the engineered data
df = pd.read_parquet('../../Data/Merged_Data/eaglei_noaa_era5_engineered.parquet')

# Restrict df to years prior to 2022 and after 2019
df = df[df['YEAR'] < 2022]
df = df[df['YEAR'] > 2019]

# We'll focus on Maine, Oregon, Arizona, Nebraska, and South Carolina
df = df[df['STUSPS'].isin(['ME', 'OR', 'AZ', 'NE', 'SC'])]

# Create a new variable 'customers_out_prop" by dividing customers_out by POPULATION
df['customers_out_prop'] = df['customers_out'] / df['POPULATION']

# Create a new variable dividing POPULATION divided by AREA
df['density'] = df['POPULATION'] / df['AREA']

# Note: Not currently including Subregion b/c we'd need to convert to a dummy variable

features_ts = ['event_count SnowIce',
       'event_count Flood', 'event_count Storm', 'event_count Hurricane',
       'event_count Heat', 'event_count Fire', 'event_count Wind',
       'event_count Ocean', 'event_count Other', 't2m', 'sf', 'tp', 't2m_mean',
       't2m_max', 'sf_mean', 'sf_max', 'tp_mean', 'tp_max', 'wind_speed',
       'neighbor_mean_wind_speed', 'neighbor_max_wind_speed', 'sf_12h',
       'sf_24h', 'tp_12h', 'tp_24h']

features_static = ['Pct_Buried_Lines','centroid_longitude','centroid_latitude','density', 'POPULATION']

# --- CONFIG ---
forecast_horizon = 4
lags = 20
n_splits = 5

# --- PREP DATA ---
grouped = dict(tuple(df.groupby('fips_code')))
fips_codes = list(grouped.keys())

series_list, cov_list, static_list = [], [], []

for fips, grp in grouped.items():
    grp = grp.sort_values('datetime')
    ts_target = TimeSeries.from_dataframe(grp, 'datetime', 'customers_out_prop')
    ts_covs = TimeSeries.from_dataframe(grp, 'datetime', features_ts)
    
    series_list.append(ts_target)
    cov_list.append(ts_covs)
    static_list.append(grp[features_static].iloc[0])

# Scale
target_scaler = Scaler()
cov_scaler = Scaler()
series_scaled = target_scaler.fit_transform(series_list)
cov_scaled = cov_scaler.fit_transform(cov_list)

# Attach static covariates
for ts, static in zip(series_scaled, static_list):
    ts = ts.with_static_covariates(static)

# Create max-over-horizon targets
def to_max_series(series, horizon):
    y = [np.max(series[i+1:i+1+horizon].values()) for i in range(len(series)-horizon)]
    time_index = series[:-horizon].time_index
    return TimeSeries.from_times_and_values(time_index, y, static_covariates=series.static_covariates)

target_max = [to_max_series(ts, forecast_horizon) for ts in series_scaled]
cov_trimmed = [ts[:-forecast_horizon] for ts in cov_scaled]

# --- TIME SPLITS ---
tscv = TimeSeriesSplit(n_splits=n_splits)
indices = list(tscv.split(target_max[0]))

# --- RESULTS CONTAINER ---
results = []
final_model = None

# --- CROSS-VALIDATION LOOP ---
for fold, (train_idx, val_idx) in enumerate(tqdm(indices, desc="CV Folds")):
    # Use a reference series to get actual time ranges
    reference_times = target_max[0].time_index
    train_start = reference_times[train_idx[0]]
    train_end = reference_times[train_idx[-1]]
    val_start = reference_times[val_idx[0]]
    val_end = reference_times[val_idx[-1]]

    # Slice all series by time
    train_series = [ts.slice(train_start, train_end) for ts in target_max]
    val_series = [ts.slice(val_start, val_end) for ts in target_max]
    train_covs = [ts.slice(train_start, train_end) for ts in cov_trimmed]
    val_covs = [ts.slice(val_start, val_end) for ts in cov_trimmed]

    model = RegressionModel(
        model=XGBRegressor(n_jobs=-1, random_state=random_state),
        lags=lags,
        lags_past_covariates=lags,
        output_chunk_length=forecast_horizon,
        use_static_covariates=True,
        multi_models=False,
    )

    # Fit once (global)
    model.fit(series=train_series, past_covariates=train_covs, verbose=False)
    final_model = model  # Store last model

    # --- PREDICT PARALLELIZED ---
    def predict_one(i):
        fips = fips_codes[i]
        ts_input = train_series[i]
        cov_full = cov_trimmed[i]

        try:
            print(f"\n[DEBUG] Testing prediction for fips_code={fips}")

            # Basic test prediction — no start time
            pred = model.predict(
                n=forecast_horizon,
                series=ts_input,
                past_covariates=cov_full,
                show_warnings=False
            )

            print(f"[DEBUG] Got prediction for fips_code={fips}: length={len(pred)}")
            print(f"[DEBUG] Prediction values:\n{pred.values()}")

            return [{
                "fips_code": fips,
                "fold": fold,
                "predicted_max": float(pred.values().max()),
                "true_max": None,
                "datetime": ts_input.end_time().to_pydatetime()
            }]

        except Exception as e:
            print(f"[ERROR] fips_code={fips}: {e}")
            return []


    fold_results = Parallel(n_jobs=-1, backend="loky")(delayed(predict_one)(i) for i in range(len(series_list)))
    results.extend([item for sublist in fold_results for item in sublist])

# --- BUILD RESULTS DATAFRAME ---
cv_results_df = pd.DataFrame(results)

# --- FINAL REGRESSOR PARAMS ---
regressor_params = final_model.model.get_params()

# Output
cv_results_df.head(), regressor_params


Exception ignored in: <function ResourceTracker.__del__ at 0x106fa6a20>
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x106a5ea20>
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_


[DEBUG] Testing prediction for fips_code=4003
[DEBUG] Got prediction for fips_code=4003: length=4

[DEBUG] Testing prediction for fips_code=4001
[DEBUG] Prediction values:
[[ 0.00278093]
 [-0.01505762]
 [-0.02326078]
 [ 0.08019005]]

[DEBUG] Testing prediction for fips_code=4005
[DEBUG] Got prediction for fips_code=4001: length=4
[DEBUG] Prediction values:
[[-0.00711255]
 [-0.00882732]
 [-0.01959416]
 [ 0.00099299]]
[DEBUG] Got prediction for fips_code=4005: length=4
[DEBUG] Prediction values:
[[ 0.006242  ]
 [-0.01174934]
 [-0.00872862]
 [ 0.00469068]]

[DEBUG] Testing prediction for fips_code=4007
[DEBUG] Got prediction for fips_code=4007: length=4
[DEBUG] Prediction values:
[[ 0.00674986]
 [ 0.00083857]
 [-0.00849574]
 [ 0.00049601]]

[DEBUG] Testing prediction for fips_code=4009
[DEBUG] Got prediction for fips_code=4009: length=4
[DEBUG] Prediction values:
[[ 0.00165747]
 [-0.01825355]
 [-0.02511141]
 [ 0.07229721]]

[DEBUG] Testing prediction for fips_code=4019
[DEBUG] Got predic

Exception ignored in: <function ResourceTracker.__del__ at 0x10750aa20>
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes



[DEBUG] Testing prediction for fips_code=23001
[DEBUG] Got prediction for fips_code=23001: length=4
[DEBUG] Prediction values:
[[0.00443702]
 [0.01892184]
 [0.00898633]
 [0.12932625]]

[DEBUG] Testing prediction for fips_code=23003
[DEBUG] Got prediction for fips_code=23003: length=4
[DEBUG] Prediction values:
[[ 0.00091636]
 [ 0.02282647]
 [-0.00120429]
 [ 0.00256733]]


/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(



[DEBUG] Testing prediction for fips_code=23005
[DEBUG] Got prediction for fips_code=23005: length=4
[DEBUG] Prediction values:
[[0.00505386]
 [0.00757437]
 [0.0133727 ]
 [0.12689316]]


Exception ignored in: <function ResourceTracker.__del__ at 0x110432a20>
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes



[DEBUG] Testing prediction for fips_code=23007
[DEBUG] Got prediction for fips_code=23007: length=4
[DEBUG] Prediction values:
[[0.00251132]
 [0.00485433]
 [0.00632499]
 [0.02920015]]

[DEBUG] Testing prediction for fips_code=23009
[DEBUG] Got prediction for fips_code=23009: length=4
[DEBUG] Prediction values:
[[0.0046403 ]
 [0.00375847]
 [0.00040697]
 [0.01267042]]

[DEBUG] Testing prediction for fips_code=23011
[DEBUG] Got prediction for fips_code=23011: length=4
[DEBUG] Prediction values:
[[0.01087399]
 [0.03673195]
 [0.01712156]
 [0.10309808]]

[DEBUG] Testing prediction for fips_code=23013
[DEBUG] Got prediction for fips_code=23013: length=4
[DEBUG] Prediction values:
[[0.00314676]
 [0.00632193]
 [0.00302579]
 [0.0589399 ]]


Exception ignored in: <function ResourceTracker.__del__ at 0x1085e2a20>
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes



[DEBUG] Testing prediction for fips_code=23017
[DEBUG] Got prediction for fips_code=23017: length=4
[DEBUG] Prediction values:
[[0.05877062]
 [0.01002334]
 [0.00721826]
 [0.08472105]]


Exception ignored in: <function ResourceTracker.__del__ at 0x107816a20>
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes



[DEBUG] Testing prediction for fips_code=23021
[DEBUG] Got prediction for fips_code=23021: length=4
[DEBUG] Prediction values:
[[0.00538172]
 [0.03481313]
 [0.001583  ]
 [0.00565304]]

[DEBUG] Testing prediction for fips_code=23023
[DEBUG] Got prediction for fips_code=23023: length=4
[DEBUG] Prediction values:
[[-0.00098233]
 [ 0.01323614]
 [ 0.01310502]
 [ 0.06152117]]


Exception ignored in: <function ResourceTracker.__del__ at 0x10491aa20>
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes



[DEBUG] Testing prediction for fips_code=23027
[DEBUG] Got prediction for fips_code=23027: length=4
[DEBUG] Prediction values:
[[0.00232423]
 [0.00608188]
 [0.00248151]
 [0.04281308]]

[DEBUG] Testing prediction for fips_code=23029
[DEBUG] Got prediction for fips_code=23029: length=4
[DEBUG] Prediction values:
[[ 0.00497089]
 [ 0.00297682]
 [-0.00122653]
 [-0.0016535 ]]


Exception ignored in: <function ResourceTracker.__del__ at 0x106e5ea20>
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes



[DEBUG] Testing prediction for fips_code=23031
[DEBUG] Got prediction for fips_code=23031: length=4
[DEBUG] Prediction values:
[[0.00262457]
 [0.00746679]
 [0.04180861]
 [0.06428406]]

[DEBUG] Testing prediction for fips_code=31001
[DEBUG] Got prediction for fips_code=31001: length=4
[DEBUG] Prediction values:
[[ 0.08104157]
 [-0.01499121]
 [-0.01057604]
 [-0.04978099]]


Exception ignored in: <function ResourceTracker.__del__ at 0x107162a20>
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes



[DEBUG] Testing prediction for fips_code=31007
[DEBUG] Got prediction for fips_code=31007: length=4
[DEBUG] Prediction values:
[[ 0.25114083]
 [-0.0233462 ]
 [ 0.02161648]
 [ 0.10204911]]

[DEBUG] Testing prediction for fips_code=31009
[DEBUG] Got prediction for fips_code=31009: length=4
[DEBUG] Prediction values:
[[ 0.05289339]
 [-0.01718116]
 [-0.01295919]
 [-0.01028678]]


Exception ignored in: <function ResourceTracker.__del__ at 0x103816a20>
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes



[DEBUG] Testing prediction for fips_code=23015
[DEBUG] Got prediction for fips_code=23015: length=4
[DEBUG] Prediction values:
[[0.00293095]
 [0.02046199]
 [0.01242075]
 [0.04923509]]

[DEBUG] Testing prediction for fips_code=31013
[DEBUG] Got prediction for fips_code=31013: length=4
[DEBUG] Prediction values:
[[ 0.0876573 ]
 [-0.02298365]
 [-0.00277607]
 [ 0.27733293]]

[DEBUG] Testing prediction for fips_code=23019
[DEBUG] Got prediction for fips_code=23019: length=4
[DEBUG] Prediction values:
[[ 0.00370326]
 [ 0.01495101]
 [-0.00018976]
 [ 0.02757722]]

[DEBUG] Testing prediction for fips_code=31015
[DEBUG] Got prediction for fips_code=31015: length=4
[DEBUG] Prediction values:
[[ 0.00620146]
 [-0.00613387]
 [ 0.0612143 ]
 [-0.00562543]]


Exception ignored in: <function ResourceTracker.__del__ at 0x10726ea20>
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes



[DEBUG] Testing prediction for fips_code=31019
[DEBUG] Got prediction for fips_code=31019: length=4
[DEBUG] Prediction values:
[[ 0.0652043 ]
 [-0.01608687]
 [-0.01214155]
 [-0.00768975]]


Exception ignored in: <function ResourceTracker.__del__ at 0x105382a20>
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes



[DEBUG] Testing prediction for fips_code=23025
[DEBUG] Got prediction for fips_code=23025: length=4
[DEBUG] Prediction values:
[[0.00806595]
 [0.01208977]
 [0.00478334]
 [0.02732921]]

[DEBUG] Testing prediction for fips_code=31023
[DEBUG] Got prediction for fips_code=31023: length=4
[DEBUG] Prediction values:
[[ 0.07438568]
 [-0.00943704]
 [-0.01809388]
 [-0.00825811]]

[DEBUG] Testing prediction for fips_code=31025
[DEBUG] Got prediction for fips_code=31025: length=4
[DEBUG] Prediction values:
[[ 0.20411348]
 [ 0.04702209]
 [ 0.02057647]
 [-0.0462518 ]]

[DEBUG] Testing prediction for fips_code=31031
[DEBUG] Got prediction for fips_code=31031: length=4
[DEBUG] Prediction values:
[[-0.01606429]
 [ 0.04992918]
 [-0.00558424]
 [ 0.03472555]]

[DEBUG] Testing prediction for fips_code=31035
[DEBUG] Got prediction for fips_code=31035: length=4
[DEBUG] Prediction values:
[[ 0.06257763]
 [-0.00414381]
 [-0.01840412]
 [-0.01011802]]

[DEBUG] Testing prediction for fips_code=31003
[DEBUG] Got

Exception ignored in: <function ResourceTracker.__del__ at 0x103b12a20>
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes



[DEBUG] Testing prediction for fips_code=31061
[DEBUG] Got prediction for fips_code=31061: length=4
[DEBUG] Prediction values:
[[ 0.0779485 ]
 [ 0.00119106]
 [-0.01301815]
 [-0.04793068]]

[DEBUG] Testing prediction for fips_code=31027
[DEBUG] Got prediction for fips_code=31027: length=4
[DEBUG] Prediction values:
[[-0.001802  ]
 [ 0.12307904]
 [ 0.06657968]
 [ 0.0295305 ]]

[DEBUG] Testing prediction for fips_code=31063
[DEBUG] Got prediction for fips_code=31063: length=4
[DEBUG] Prediction values:
[[ 0.28363827]
 [-0.01735667]
 [-0.01871375]
 [-0.00765718]]

[DEBUG] Testing prediction for fips_code=31065
[DEBUG] Got prediction for fips_code=31065: length=4
[DEBUG] Prediction values:
[[ 0.2777896 ]
 [-0.02045229]
 [-0.01377828]
 [-0.00245757]]

[DEBUG] Testing prediction for fips_code=31067
[DEBUG] Got prediction for fips_code=31067: length=4
[DEBUG] Prediction values:
[[ 0.02792102]
 [-0.00308825]
 [ 0.02404781]
 [-0.04930147]]


Exception ignored in: <function ResourceTracker.__del__ at 0x114216a20>
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes



[DEBUG] Testing prediction for fips_code=31073
[DEBUG] Got prediction for fips_code=31073: length=4
[DEBUG] Prediction values:
[[ 0.28475016]
 [-0.01649863]
 [-0.01586118]
 [-0.04619329]]

[DEBUG] Testing prediction for fips_code=31075
[DEBUG] Got prediction for fips_code=31075: length=4
[DEBUG] Prediction values:
[[ 0.19337575]
 [-0.01699949]
 [-0.00447673]
 [ 0.25574225]]


Exception ignored in: <function ResourceTracker.__del__ at 0x107196a20>
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes



[DEBUG] Testing prediction for fips_code=31077
[DEBUG] Got prediction for fips_code=31077: length=4
[DEBUG] Prediction values:
[[ 0.05700144]
 [-0.02521226]
 [-0.01291194]
 [-0.00673603]]

[DEBUG] Testing prediction for fips_code=31079
[DEBUG] Got prediction for fips_code=31079: length=4
[DEBUG] Prediction values:
[[ 0.06932661]
 [-0.01665803]
 [-0.01132797]
 [-0.0497383 ]]

[DEBUG] Testing prediction for fips_code=31049
[DEBUG] Got prediction for fips_code=31049: length=4
[DEBUG] Prediction values:
[[-0.00105396]
 [-0.02766802]
 [-0.01727945]
 [ 0.15358809]]


Exception ignored in: <function ResourceTracker.__del__ at 0x102d16a20>
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes



[DEBUG] Testing prediction for fips_code=31083
[DEBUG] Got prediction for fips_code=31083: length=4
[DEBUG] Prediction values:
[[ 0.2933847 ]
 [-0.0134738 ]
 [-0.01110707]
 [-0.00463983]]

[DEBUG] Testing prediction for fips_code=31085
[DEBUG] Got prediction for fips_code=31085: length=4
[DEBUG] Prediction values:
[[ 0.2658522 ]
 [-0.02384667]
 [-0.01853949]
 [ 0.07876255]]

[DEBUG] Testing prediction for fips_code=31087
[DEBUG] Got prediction for fips_code=31087: length=4
[DEBUG] Prediction values:
[[-0.01325657]
 [-0.01844693]
 [-0.02017211]
 [-0.00992612]]

[DEBUG] Testing prediction for fips_code=31089
[DEBUG] Got prediction for fips_code=31089: length=4
[DEBUG] Prediction values:
[[ 0.00645587]
 [-0.01905953]
 [-0.00509632]
 [-0.00824023]]

[DEBUG] Testing prediction for fips_code=31093
[DEBUG] Got prediction for fips_code=31093: length=4
[DEBUG] Prediction values:
[[ 0.05526362]
 [-0.016713  ]
 [-0.01117801]
 [-0.00753331]]

[DEBUG] Testing prediction for fips_code=31097
[DEBUG]

Exception ignored in: <function ResourceTracker.__del__ at 0x1030f2a20>
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes



[DEBUG] Testing prediction for fips_code=31131
[DEBUG] Got prediction for fips_code=31131: length=4
[DEBUG] Prediction values:
[[ 0.17324662]
 [ 0.04699526]
 [-0.00329311]
 [-0.04089307]]

[DEBUG] Testing prediction for fips_code=31133
[DEBUG] Got prediction for fips_code=31133: length=4
[DEBUG] Prediction values:
[[ 0.10585136]
 [-0.01085876]
 [-0.00602676]
 [-0.04513379]]

[DEBUG] Testing prediction for fips_code=31135
[DEBUG] Got prediction for fips_code=31135: length=4
[DEBUG] Prediction values:
[[ 0.2602243 ]
 [-0.02045094]
 [-0.01739695]
 [ 0.10820083]]

[DEBUG] Testing prediction for fips_code=31101
[DEBUG] Got prediction for fips_code=31101: length=4
[DEBUG] Prediction values:
[[ 0.20165509]
 [-0.02458894]
 [-0.01887387]
 [ 0.08123165]]

[DEBUG] Testing prediction for fips_code=31137
[DEBUG] Got prediction for fips_code=31137: length=4
[DEBUG] Prediction values:
[[ 0.06885791]
 [ 0.00075147]
 [-0.0063853 ]
 [-0.04731577]]

[DEBUG] Testing prediction for fips_code=31139
[DEBUG]

Exception ignored in: <function ResourceTracker.__del__ at 0x10337ea20>
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes



[DEBUG] Testing prediction for fips_code=31151
[DEBUG] Got prediction for fips_code=31151: length=4
[DEBUG] Prediction values:
[[ 0.07281833]
 [-0.00557101]
 [ 0.02100301]
 [-0.01233355]]

[DEBUG] Testing prediction for fips_code=31153
[DEBUG] Got prediction for fips_code=31153: length=4
[DEBUG] Prediction values:
[[ 0.19310251]
 [ 0.05315245]
 [ 0.01470872]
 [-0.04834612]]

[DEBUG] Testing prediction for fips_code=31157
[DEBUG] Got prediction for fips_code=31157: length=4
[DEBUG] Prediction values:
[[ 0.30086112]
 [-0.02399905]
 [-0.00269917]
 [ 0.25006557]]

[DEBUG] Testing prediction for fips_code=31159
[DEBUG] Got prediction for fips_code=31159: length=4
[DEBUG] Prediction values:
[[ 0.10887333]
 [ 0.02099759]
 [ 0.04142056]
 [-0.01768583]]

[DEBUG] Testing prediction for fips_code=31161
[DEBUG] Got prediction for fips_code=31161: length=4
[DEBUG] Prediction values:
[[ 0.04369688]
 [-0.02076028]
 [-0.0028824 ]
 [ 0.17742822]]

[DEBUG] Testing prediction for fips_code=31163
[DEBUG]

Exception ignored in: <function ResourceTracker.__del__ at 0x106716a20>
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes



[DEBUG] Testing prediction for fips_code=31173
[DEBUG] Got prediction for fips_code=31173: length=4
[DEBUG] Prediction values:
[[ 0.24226274]
 [ 0.04671126]
 [ 0.06687826]
 [-0.00902814]]

[DEBUG] Testing prediction for fips_code=31175
[DEBUG] Got prediction for fips_code=31175: length=4
[DEBUG] Prediction values:
[[ 0.07236503]
 [-0.02594058]
 [ 0.01538559]
 [-0.00717532]]

[DEBUG] Testing prediction for fips_code=31177
[DEBUG] Got prediction for fips_code=31177: length=4
[DEBUG] Prediction values:
[[ 0.13945548]
 [ 0.06601203]
 [ 0.01861527]
 [-0.04765487]]

[DEBUG] Testing prediction for fips_code=31179
[DEBUG] Got prediction for fips_code=31179: length=4
[DEBUG] Prediction values:
[[ 0.15350613]
 [ 0.05014496]
 [ 0.08477588]
 [-0.00816418]]

[DEBUG] Testing prediction for fips_code=31155
[DEBUG] Got prediction for fips_code=31155: length=4
[DEBUG] Prediction values:
[[ 0.16209275]
 [ 0.05246985]
 [ 0.01825136]
 [-0.01261416]]

[DEBUG] Testing prediction for fips_code=41003
[DEBUG]

Exception ignored in: <function ResourceTracker.__del__ at 0x1076d2a20>
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes



[DEBUG] Testing prediction for fips_code=45005
[DEBUG] Got prediction for fips_code=45005: length=4
[DEBUG] Prediction values:
[[-0.00407951]
 [ 0.00236271]
 [-0.00095741]
 [-0.00199576]]

[DEBUG] Testing prediction for fips_code=45007
[DEBUG] Got prediction for fips_code=45007: length=4
[DEBUG] Prediction values:
[[ 0.00308592]
 [-0.00138731]
 [ 0.00076267]
 [ 0.09385978]]

[DEBUG] Testing prediction for fips_code=45009
[DEBUG] Got prediction for fips_code=45009: length=4
[DEBUG] Prediction values:
[[-0.00065468]
 [ 0.01207066]
 [ 0.04043612]
 [ 0.00127382]]

[DEBUG] Testing prediction for fips_code=45011
[DEBUG] Got prediction for fips_code=45011: length=4
[DEBUG] Prediction values:
[[-0.00511418]
 [ 0.00662933]
 [-0.00013602]
 [-0.00140035]]

[DEBUG] Testing prediction for fips_code=45013
[DEBUG] Got prediction for fips_code=45013: length=4
[DEBUG] Prediction values:
[[0.03442862]
 [0.0095093 ]
 [0.02030247]
 [0.00494965]]

[DEBUG] Testing prediction for fips_code=45015
[DEBUG] Got

Exception ignored in: <function ResourceTracker.__del__ at 0x11a216a20>
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes



[DEBUG] Testing prediction for fips_code=45017
[DEBUG] Got prediction for fips_code=45017: length=4
[DEBUG] Prediction values:
[[0.00650899]
 [0.02195753]
 [0.00725812]
 [0.00470592]]

[DEBUG] Testing prediction for fips_code=45019
[DEBUG] Got prediction for fips_code=45019: length=4
[DEBUG] Prediction values:
[[0.00478948]
 [0.01362226]
 [0.01393127]
 [0.01014502]]

[DEBUG] Testing prediction for fips_code=45021
[DEBUG] Got prediction for fips_code=45021: length=4
[DEBUG] Prediction values:
[[-0.00148135]
 [ 0.02149777]
 [-0.00119467]
 [-0.00039492]]


Exception ignored in: <function ResourceTracker.__del__ at 0x10306aa20>
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes



[DEBUG] Testing prediction for fips_code=45023
[DEBUG] Got prediction for fips_code=45023: length=4
[DEBUG] Prediction values:
[[ 0.00560078]
 [ 0.00417589]
 [-0.00046723]
 [-0.0018637 ]]

[DEBUG] Testing prediction for fips_code=45031
[DEBUG] Got prediction for fips_code=45031: length=4
[DEBUG] Prediction values:
[[0.01322151]
 [0.02590013]
 [0.03894685]
 [0.01037819]]

[DEBUG] Testing prediction for fips_code=45033
[DEBUG] Got prediction for fips_code=45033: length=4
[DEBUG] Prediction values:
[[0.11983911]
 [0.01743495]
 [0.00313903]
 [0.00566634]]

[DEBUG] Testing prediction for fips_code=45035
[DEBUG] Got prediction for fips_code=45035: length=4
[DEBUG] Prediction values:
[[0.00775196]
 [0.00890252]
 [0.00778762]
 [0.00652403]]

[DEBUG] Testing prediction for fips_code=45037
[DEBUG] Got prediction for fips_code=45037: length=4
[DEBUG] Prediction values:
[[ 0.02279427]
 [ 0.01747963]
 [-0.00746214]
 [ 0.00088148]]

[DEBUG] Testing prediction for fips_code=45039
[DEBUG] Got predict

Exception ignored in: <function ResourceTracker.__del__ at 0x103a12a20>
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes



[DEBUG] Testing prediction for fips_code=45081
[DEBUG] Got prediction for fips_code=45081: length=4
[DEBUG] Prediction values:
[[ 0.00359752]
 [ 0.0062735 ]
 [-0.00786381]
 [ 0.00042377]]

[DEBUG] Testing prediction for fips_code=45083
[DEBUG] Got prediction for fips_code=45083: length=4
[DEBUG] Prediction values:
[[ 0.00185711]
 [ 0.01129568]
 [-0.00026437]
 [ 0.01939388]]

[DEBUG] Testing prediction for fips_code=45085
[DEBUG] Got prediction for fips_code=45085: length=4
[DEBUG] Prediction values:
[[0.02264136]
 [0.00966391]
 [0.01836503]
 [0.00156137]]

[DEBUG] Testing prediction for fips_code=45087
[DEBUG] Got prediction for fips_code=45087: length=4
[DEBUG] Prediction values:
[[-0.00122455]
 [-0.00458339]
 [-0.00156909]
 [-0.00069002]]

[DEBUG] Testing prediction for fips_code=45089
[DEBUG] Got prediction for fips_code=45089: length=4
[DEBUG] Prediction values:
[[-0.00200292]
 [ 0.02238468]
 [ 0.01727775]
 [ 0.01970189]]


CV Folds:  20%|██        | 1/5 [01:04<04:17, 64.26s/it]


[DEBUG] Testing prediction for fips_code=45091
[DEBUG] Got prediction for fips_code=45091: length=4
[DEBUG] Prediction values:
[[ 0.00158016]
 [ 0.00448048]
 [-0.00157879]
 [-0.00081414]]

[DEBUG] Testing prediction for fips_code=4001
[DEBUG] Got prediction for fips_code=4001: length=4
[DEBUG] Prediction values:
[[0.0050077 ]
 [0.00682805]
 [0.0063494 ]
 [0.00445881]]

[DEBUG] Testing prediction for fips_code=4003
[DEBUG] Got prediction for fips_code=4003: length=4
[DEBUG] Prediction values:
[[ 0.01340354]
 [-0.00021274]
 [ 0.01169742]
 [ 0.00814341]]

[DEBUG] Testing prediction for fips_code=4005
[DEBUG] Got prediction for fips_code=4005: length=4
[DEBUG] Prediction values:
[[0.01041325]
 [0.01910899]
 [0.01107447]
 [0.01317811]]

[DEBUG] Testing prediction for fips_code=4007
[DEBUG] Got prediction for fips_code=4007: length=4
[DEBUG] Prediction values:
[[0.02456637]
 [0.03282512]
 [0.03374044]
 [0.04338542]]

[DEBUG] Testing prediction for fips_code=4009
[DEBUG] Got prediction for f

Exception ignored in: <function ResourceTracker.__del__ at 0x10343aa20>
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes



[DEBUG] Testing prediction for fips_code=23003
[DEBUG] Got prediction for fips_code=23003: length=4
[DEBUG] Prediction values:
[[ 0.004231  ]
 [ 0.00032889]
 [-0.00020213]
 [-0.00404012]]

[DEBUG] Testing prediction for fips_code=23005
[DEBUG] Got prediction for fips_code=23005: length=4
[DEBUG] Prediction values:
[[0.01042397]
 [0.00797612]
 [0.00972727]
 [0.01806669]]

[DEBUG] Testing prediction for fips_code=23007
[DEBUG] Got prediction for fips_code=23007: length=4
[DEBUG] Prediction values:
[[-0.0018701 ]
 [ 0.0013152 ]
 [ 0.00194542]
 [-0.00207073]]

[DEBUG] Testing prediction for fips_code=23009
[DEBUG] Got prediction for fips_code=23009: length=4
[DEBUG] Prediction values:
[[0.00038528]
 [0.01833685]
 [0.00719254]
 [0.0097781 ]]

[DEBUG] Testing prediction for fips_code=23013
[DEBUG] Got prediction for fips_code=23013: length=4
[DEBUG] Prediction values:
[[0.00274286]
 [0.00814662]
 [0.00629167]
 [0.00704082]]

[DEBUG] Testing prediction for fips_code=23015
[DEBUG] Got predict

Exception ignored in: <function ResourceTracker.__del__ at 0x102c62a20>
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes



[DEBUG] Testing prediction for fips_code=31039
[DEBUG] Got prediction for fips_code=31039: length=4
[DEBUG] Prediction values:
[[ 0.00440463]
 [ 0.00110267]
 [-0.00087136]
 [ 0.00201459]]

[DEBUG] Testing prediction for fips_code=31041
[DEBUG] Got prediction for fips_code=31041: length=4
[DEBUG] Prediction values:
[[ 0.00493909]
 [-0.00255319]
 [ 0.00034455]
 [ 0.00252716]]

[DEBUG] Testing prediction for fips_code=31043
[DEBUG] Got prediction for fips_code=31043: length=4
[DEBUG] Prediction values:
[[-0.00619048]
 [-0.0023927 ]
 [ 0.00159158]
 [ 0.00219839]]

[DEBUG] Testing prediction for fips_code=31045
[DEBUG] Got prediction for fips_code=31045: length=4
[DEBUG] Prediction values:
[[0.00316546]
 [0.00709779]
 [0.00430211]
 [0.00059492]]

[DEBUG] Testing prediction for fips_code=31047
[DEBUG] Got prediction for fips_code=31047: length=4
[DEBUG] Prediction values:
[[-0.00095057]
 [-0.0001428 ]
 [ 0.00255905]
 [ 0.00181717]]

[DEBUG] Testing prediction for fips_code=31049
[DEBUG] Got

Exception ignored in: <function ResourceTracker.__del__ at 0x104716a20>
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes



[DEBUG] Testing prediction for fips_code=31053
[DEBUG] Got prediction for fips_code=31053: length=4
[DEBUG] Prediction values:
[[0.0021465 ]
 [0.00467294]
 [0.00107566]
 [0.00309487]]

[DEBUG] Testing prediction for fips_code=31055
[DEBUG] Got prediction for fips_code=31055: length=4
[DEBUG] Prediction values:
[[0.00087082]
 [0.00112678]
 [0.00070678]
 [0.00362023]]

[DEBUG] Testing prediction for fips_code=31061
[DEBUG] Got prediction for fips_code=31061: length=4
[DEBUG] Prediction values:
[[ 0.00031661]
 [ 0.00334166]
 [-0.00092893]
 [-0.00051821]]

[DEBUG] Testing prediction for fips_code=31063
[DEBUG] Got prediction for fips_code=31063: length=4
[DEBUG] Prediction values:
[[-0.00179345]
 [ 0.00512834]
 [ 0.00029889]
 [-0.0005423 ]]

[DEBUG] Testing prediction for fips_code=31067
[DEBUG] Got prediction for fips_code=31067: length=4
[DEBUG] Prediction values:
[[ 0.00527882]
 [-0.00249756]
 [ 0.00375686]
 [ 0.01254013]]

[DEBUG] Testing prediction for fips_code=31069
[DEBUG] Got pre

Exception ignored in: <function ResourceTracker.__del__ at 0x1075caa20>
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes



[DEBUG] Testing prediction for fips_code=31115
[DEBUG] Got prediction for fips_code=31115: length=4
[DEBUG] Prediction values:
[[-0.00049654]
 [-0.00112143]
 [ 0.0038709 ]
 [-0.00203636]]

[DEBUG] Testing prediction for fips_code=31117
[DEBUG] Got prediction for fips_code=31117: length=4
[DEBUG] Prediction values:
[[ 0.06716859]
 [-0.00196682]
 [ 0.00442392]
 [-0.00143409]]

[DEBUG] Testing prediction for fips_code=31119
[DEBUG] Got prediction for fips_code=31119: length=4
[DEBUG] Prediction values:
[[-0.00259471]
 [ 0.00465732]
 [-0.00346695]
 [-0.00582648]]

[DEBUG] Testing prediction for fips_code=31123
[DEBUG] Got prediction for fips_code=31123: length=4
[DEBUG] Prediction values:
[[0.00137532]
 [0.00137541]
 [0.00296625]
 [0.00178213]]

[DEBUG] Testing prediction for fips_code=31127
[DEBUG] Got prediction for fips_code=31127: length=4
[DEBUG] Prediction values:
[[-0.00350831]
 [ 0.00659404]
 [ 0.009668  ]
 [ 0.00574068]]

[DEBUG] Testing prediction for fips_code=31131
[DEBUG] Got

Exception ignored in: <function ResourceTracker.__del__ at 0x106fbea20>
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes



[DEBUG] Testing prediction for fips_code=31149
[DEBUG] Got prediction for fips_code=31149: length=4
[DEBUG] Prediction values:
[[-0.00743155]
 [-0.00036011]
 [ 0.01068302]
 [-0.00456316]]

[DEBUG] Testing prediction for fips_code=31153
[DEBUG] Got prediction for fips_code=31153: length=4
[DEBUG] Prediction values:
[[0.00740553]
 [0.00725038]
 [0.02691164]
 [0.0055178 ]]

[DEBUG] Testing prediction for fips_code=31155
[DEBUG] Got prediction for fips_code=31155: length=4
[DEBUG] Prediction values:
[[ 0.00453526]
 [ 0.00348743]
 [ 0.00098528]
 [-0.00035971]]

[DEBUG] Testing prediction for fips_code=31157
[DEBUG] Got prediction for fips_code=31157: length=4
[DEBUG] Prediction values:
[[0.01730355]
 [0.01399816]
 [0.01314757]
 [0.0032838 ]]

[DEBUG] Testing prediction for fips_code=31159
[DEBUG] Got prediction for fips_code=31159: length=4
[DEBUG] Prediction values:
[[0.00927736]
 [0.01558656]
 [0.01205903]
 [0.01968435]]

[DEBUG] Testing prediction for fips_code=31163
[DEBUG] Got predict

Exception ignored in: <function ResourceTracker.__del__ at 0x106d82a20>
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes



[DEBUG] Testing prediction for fips_code=41057
[DEBUG] Got prediction for fips_code=41057: length=4
[DEBUG] Prediction values:
[[0.00590554]
 [0.0044136 ]
 [0.00680016]
 [0.00032664]]

[DEBUG] Testing prediction for fips_code=41059
[DEBUG] Got prediction for fips_code=41059: length=4
[DEBUG] Prediction values:
[[0.00374112]
 [0.00447101]
 [0.00658903]
 [0.00916872]]

[DEBUG] Testing prediction for fips_code=41061
[DEBUG] Got prediction for fips_code=41061: length=4
[DEBUG] Prediction values:
[[ 0.00093699]
 [-0.00507354]
 [-0.00115968]
 [-0.00171123]]

[DEBUG] Testing prediction for fips_code=41063
[DEBUG] Got prediction for fips_code=41063: length=4
[DEBUG] Prediction values:
[[0.00643886]
 [0.005107  ]
 [0.00653753]
 [0.00903611]]

[DEBUG] Testing prediction for fips_code=41065
[DEBUG] Got prediction for fips_code=41065: length=4
[DEBUG] Prediction values:
[[-0.00331882]
 [-0.02527287]
 [-0.00129111]
 [ 0.00282692]]


Exception ignored in: <function ResourceTracker.__del__ at 0x107112a20>
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes



[DEBUG] Testing prediction for fips_code=41071
[DEBUG] Got prediction for fips_code=41071: length=4
[DEBUG] Prediction values:
[[0.00178894]
 [0.00441644]
 [0.00157063]
 [0.0054912 ]]

[DEBUG] Testing prediction for fips_code=45001
[DEBUG] Got prediction for fips_code=45001: length=4
[DEBUG] Prediction values:
[[0.01101239]
 [0.01185327]
 [0.01038795]
 [0.0083312 ]]

[DEBUG] Testing prediction for fips_code=45003
[DEBUG] Got prediction for fips_code=45003: length=4
[DEBUG] Prediction values:
[[0.00425933]
 [0.01007564]
 [0.00838514]
 [0.01128201]]

[DEBUG] Testing prediction for fips_code=45005
[DEBUG] Got prediction for fips_code=45005: length=4
[DEBUG] Prediction values:
[[0.00605757]
 [0.00847138]
 [0.0041853 ]
 [0.00660242]]

[DEBUG] Testing prediction for fips_code=45007
[DEBUG] Got prediction for fips_code=45007: length=4
[DEBUG] Prediction values:
[[0.01334158]
 [0.015095  ]
 [0.0058783 ]
 [0.00744553]]

[DEBUG] Testing prediction for fips_code=45009
[DEBUG] Got prediction for 

Exception ignored in: <function ResourceTracker.__del__ at 0x10372ea20>
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes



[DEBUG] Testing prediction for fips_code=45037
[DEBUG] Got prediction for fips_code=45037: length=4
[DEBUG] Prediction values:
[[0.00745757]
 [0.00532656]
 [0.01141858]
 [0.01416543]]

[DEBUG] Testing prediction for fips_code=45039
[DEBUG] Got prediction for fips_code=45039: length=4
[DEBUG] Prediction values:
[[0.00993409]
 [0.00815397]
 [0.01106704]
 [0.00476385]]

[DEBUG] Testing prediction for fips_code=45041
[DEBUG] Got prediction for fips_code=45041: length=4
[DEBUG] Prediction values:
[[0.15252322]
 [0.00763441]
 [0.02874932]
 [0.02348991]]

[DEBUG] Testing prediction for fips_code=45043
[DEBUG] Got prediction for fips_code=45043: length=4
[DEBUG] Prediction values:
[[0.01042307]
 [0.00727042]
 [0.01168882]
 [0.0122572 ]]

[DEBUG] Testing prediction for fips_code=45045
[DEBUG] Got prediction for fips_code=45045: length=4
[DEBUG] Prediction values:
[[0.01648077]
 [0.01630422]
 [0.01392658]
 [0.00985648]]

[DEBUG] Testing prediction for fips_code=45047
[DEBUG] Got prediction for 

Exception ignored in: <function ResourceTracker.__del__ at 0x107eb6a20>
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes



[DEBUG] Testing prediction for fips_code=45055
[DEBUG] Got prediction for fips_code=45055: length=4
[DEBUG] Prediction values:
[[0.01479496]
 [0.0115299 ]
 [0.02101543]
 [0.01128817]]

[DEBUG] Testing prediction for fips_code=45057
[DEBUG] Got prediction for fips_code=45057: length=4
[DEBUG] Prediction values:
[[0.00746994]
 [0.01053993]
 [0.00886633]
 [0.01137142]]

[DEBUG] Testing prediction for fips_code=45059
[DEBUG] Got prediction for fips_code=45059: length=4
[DEBUG] Prediction values:
[[0.00836857]
 [0.01415732]
 [0.01344567]
 [0.00717468]]

[DEBUG] Testing prediction for fips_code=45035
[DEBUG] Got prediction for fips_code=45035: length=4
[DEBUG] Prediction values:
[[0.0078103 ]
 [0.01081797]
 [0.00818686]
 [0.0024255 ]]

[DEBUG] Testing prediction for fips_code=45061
[DEBUG] Got prediction for fips_code=45061: length=4
[DEBUG] Prediction values:
[[0.04425735]
 [0.03219283]
 [0.03215101]
 [0.02577336]]

[DEBUG] Testing prediction for fips_code=45063
[DEBUG] Got prediction for 

Exception ignored in: <function ResourceTracker.__del__ at 0x10291aa20>
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes



[DEBUG] Testing prediction for fips_code=45073
[DEBUG] Got prediction for fips_code=45073: length=4
[DEBUG] Prediction values:
[[0.00748784]
 [0.01549194]
 [0.00761346]
 [0.00580512]]

[DEBUG] Testing prediction for fips_code=45075
[DEBUG] Got prediction for fips_code=45075: length=4
[DEBUG] Prediction values:
[[0.01437904]
 [0.01305587]
 [0.00928664]
 [0.00798929]]

[DEBUG] Testing prediction for fips_code=45077
[DEBUG] Got prediction for fips_code=45077: length=4
[DEBUG] Prediction values:
[[0.01074833]
 [0.01032092]
 [0.00678276]
 [0.00674236]]

[DEBUG] Testing prediction for fips_code=45079
[DEBUG] Got prediction for fips_code=45079: length=4
[DEBUG] Prediction values:
[[0.02053333]
 [0.01827163]
 [0.01445036]
 [0.02239629]]

[DEBUG] Testing prediction for fips_code=45085
[DEBUG] Got prediction for fips_code=45085: length=4
[DEBUG] Prediction values:
[[0.02504372]
 [0.00630871]
 [0.01671401]
 [0.02270407]]

[DEBUG] Testing prediction for fips_code=45089
[DEBUG] Got prediction for 

CV Folds:  40%|████      | 2/5 [02:04<03:05, 61.93s/it]


[DEBUG] Testing prediction for fips_code=45087
[DEBUG] Got prediction for fips_code=45087: length=4
[DEBUG] Prediction values:
[[0.011253  ]
 [0.01684745]
 [0.00522845]
 [0.00667552]]

[DEBUG] Testing prediction for fips_code=4001
[DEBUG] Got prediction for fips_code=4001: length=4
[DEBUG] Prediction values:
[[-0.0002961 ]
 [ 0.00221432]
 [ 0.00555869]
 [ 0.00447763]]

[DEBUG] Testing prediction for fips_code=4003
[DEBUG] Got prediction for fips_code=4003: length=4
[DEBUG] Prediction values:
[[-0.00505674]
 [-0.00417688]
 [ 0.00089008]
 [ 0.00213485]]

[DEBUG] Testing prediction for fips_code=4005
[DEBUG] Got prediction for fips_code=4005: length=4
[DEBUG] Prediction values:
[[-0.00057124]
 [ 0.00306764]
 [-0.00039964]
 [-0.00123899]]

[DEBUG] Testing prediction for fips_code=4007
[DEBUG] Got prediction for fips_code=4007: length=4
[DEBUG] Prediction values:
[[-0.00251108]
 [-0.00045848]
 [-0.00261114]
 [ 0.00519753]]

[DEBUG] Testing prediction for fips_code=4009
[DEBUG] Got predicti

CV Folds:  60%|██████    | 3/5 [03:03<02:00, 60.43s/it]


[DEBUG] Testing prediction for fips_code=45091
[DEBUG] Got prediction for fips_code=45091: length=4
[DEBUG] Prediction values:
[[-7.5644767e-04]
 [ 2.2917369e-03]
 [-9.7227246e-05]
 [ 5.9528085e-03]]

[DEBUG] Testing prediction for fips_code=4001
[DEBUG] Got prediction for fips_code=4001: length=4
[DEBUG] Prediction values:
[[0.00574167]
 [0.00164413]
 [0.00390128]
 [0.00695099]]

[DEBUG] Testing prediction for fips_code=4003
[DEBUG] Got prediction for fips_code=4003: length=4
[DEBUG] Prediction values:
[[-0.00153802]
 [ 0.00028735]
 [ 0.00575844]
 [ 0.00689192]]

[DEBUG] Testing prediction for fips_code=4005
[DEBUG] Got prediction for fips_code=4005: length=4
[DEBUG] Prediction values:
[[0.00559949]
 [0.00385978]
 [0.02752267]
 [0.00473734]]

[DEBUG] Testing prediction for fips_code=4007
[DEBUG] Got prediction for fips_code=4007: length=4
[DEBUG] Prediction values:
[[0.00526639]
 [0.00680137]
 [0.01744266]
 [0.01034485]]

[DEBUG] Testing prediction for fips_code=4009
[DEBUG] Got pred

CV Folds:  80%|████████  | 4/5 [04:05<01:01, 61.06s/it]


[DEBUG] Testing prediction for fips_code=45091
[DEBUG] Got prediction for fips_code=45091: length=4
[DEBUG] Prediction values:
[[0.01030662]
 [0.01691954]
 [0.0181024 ]
 [0.01789305]]

[DEBUG] Testing prediction for fips_code=4001
[DEBUG] Got prediction for fips_code=4001: length=4
[DEBUG] Prediction values:
[[0.00888751]
 [0.01163646]
 [0.01480907]
 [0.01145535]]

[DEBUG] Testing prediction for fips_code=4003
[DEBUG] Got prediction for fips_code=4003: length=4
[DEBUG] Prediction values:
[[ 0.00259885]
 [ 0.00211923]
 [-0.00030249]
 [ 0.00156354]]

[DEBUG] Testing prediction for fips_code=4005
[DEBUG] Got prediction for fips_code=4005: length=4
[DEBUG] Prediction values:
[[0.01203067]
 [0.01027678]
 [0.01200751]
 [0.00919083]]

[DEBUG] Testing prediction for fips_code=4007
[DEBUG] Got prediction for fips_code=4007: length=4
[DEBUG] Prediction values:
[[0.01598311]
 [0.01960652]
 [0.01326337]
 [0.01423602]]

[DEBUG] Testing prediction for fips_code=4009
[DEBUG] Got prediction for fips_

CV Folds: 100%|██████████| 5/5 [05:11<00:00, 62.31s/it]


[DEBUG] Testing prediction for fips_code=45091
[DEBUG] Got prediction for fips_code=45091: length=4
[DEBUG] Prediction values:
[[0.00934228]
 [0.01877396]
 [0.01179303]
 [0.01067747]]


(   fips_code  fold  predicted_max true_max            datetime
 0       4001     0       0.000993     None 2020-05-02 06:00:00
 1       4003     0       0.080190     None 2020-05-02 06:00:00
 2       4005     0       0.006242     None 2020-05-02 06:00:00
 3       4007     0       0.006750     None 2020-05-02 06:00:00
 4       4009     0       0.072297     None 2020-05-02 06:00:00,
 {'objective': 'reg:squarederror',
  'base_score': None,
  'booster': None,
  'callbacks': None,
  'colsample_bylevel': None,
  'colsample_bynode': None,
  'colsample_bytree': None,
  'device': None,
  'early_stopping_rounds': None,
  'enable_categorical': False,
  'eval_metric': None,
  'feature_types': None,
  'gamma': None,
  'grow_policy': None,
  'importance_type': None,
  'interaction_constraints': None,
  'learning_rate': None,
  'max_bin': None,
  'max_cat_threshold': None,
  'max_cat_to_onehot': None,
  'max_delta_step': None,
  'max_depth': None,
  'max_leaves': None,
  'min_child_weight': None,
  

Exception ignored in: <function ResourceTracker.__del__ at 0x107d16a20>
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x108816a20>
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/homebrew/anaconda3/envs/erdos_spring_2025/lib/python3.12/multiprocessing/resource_